#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: restore_iotstack runtag (eg yyyy-mm-dd_hhmm)"
	exit -1
fi

# define the backup host
SCPNAME="myhost.mydomain.com"
SCPUSER="myuser"
SCPPATH="/path/to/backup/directory/on/myhost"

# snapshot the current date and time
RUNTAG=$1

# IOTstack lives here
IOTSTACK="$HOME/IOTstack"

# the backup directory is
RESTOREDIR="$IOTSTACK/restore"
GENERALDIR="$RESTOREDIR/general"

GENERALBACKUP="general-backup.tar.gz"
INFLUXBACKUP="influx-backup.tar"

# create the scaffolding
mkdir -p "$GENERALDIR"

# move into the restore directory
cd "$RESTOREDIR"

# now we can begin
echo "----- Restoring backup images for $RUNTAG -----"

scp $SCPUSER@$SCPNAME:$SCPPATH/$RUNTAG.$GENERALBACKUP $GENERALBACKUP
scp $SCPUSER@$SCPNAME:$SCPPATH/$RUNTAG.$INFLUXBACKUP $INFLUXBACKUP

echo "----- Unpacking the general backup -----"

cd "$GENERALDIR"
sudo tar -x --same-owner -z -f ../$GENERALBACKUP

echo "----- deactivating the stack -----"

cd "$IOTSTACK"
docker-compose down

echo "----- removing old volumes and services directories -----"

sudo rm -rf ./services ./volumes

echo "----- moving backup volumes and services into place -----"

sudo mv ./restore/general/services .
sudo mv ./restore/general/volumes .
sudo mv ./restore/general/docker-compose.yml ./docker-compose.yml.$RUNTAG

echo "----- Unpacking the influx backup -----"

cd ./backups/influxdb/db
sudo tar -x --same-owner -f "$RESTOREDIR/$INFLUXBACKUP"

echo "----- reactivating the stack -----"

cd "$IOTSTACK"
docker-compose up -d

echo "----- reloading the influx databases -----"

docker exec influxdb influxd restore -portable /var/lib/influxdb/backup

echo "----- cleaning up -----"

rm -rf "$RESTOREDIR"

echo "Restore complete"
