#!/usr/bin/env bash

# support user renaming of script
SCRIPT=$(basename "$0")

# should not run as root
[ "$EUID" -eq 0 ] && echo "$SCRIPT should NOT be run using sudo" && exit 1

# assumptions that can be overridden
IOTSTACK=${IOTSTACK:-"$HOME/IOTstack"}
CONTAINER=${CONTAINER:-"mariadb"}
DEFAULTFILENAME=${DEFAULTFILENAME:-"$CONTAINER-backup.tar.gz"}

# the project name is the all-lower-case form of the folder name
PROJECT=$(basename ${IOTSTACK,,})

# useful function
isContainerRunning() {
   if STATUS=$(curl -s --unix-socket /var/run/docker.sock http://localhost/containers/$1/json | jq .State.Status) ; then
      if [ "$STATUS" = "\"running\"" ] ; then
         return 0
      fi
   fi
   return 1
}

preferredCommand() {
   if [ -n "$(docker exec "$CONTAINER" which "$1")" ] ; then
      echo "$1"
   else
      echo "$2"
   fi
}


# $1 is required and is either path to a .tar.gz or the path to a folder
# $2 is optional and is the runtag (yyyy-mm-dd_hhmm.host-name)
# $3 is optional and overrides the default file name

case "$#" in

  1)
    BACKUP_TAR_GZ=$(realpath "$1")
    ;;

  2 | 3)
    BACKUP_TAR_GZ=$(realpath "$1/$2.${3:-"$DEFAULTFILENAME"}")
    ;;

  *)
    echo "Usage 1: $SCRIPT path/to/$DEFAULTFILENAME"
    echo "Usage 2: $SCRIPT path/to/backupdir runtag {override}"
    echo "         (override defaults to $DEFAULTFILENAME)"
    exit 1
    ;;

esac

# fail safe if the file already exists - no accidental overwrites
if [ -e "$BACKUP_TAR_GZ" ] ; then
   echo "Error: $BACKUP_TAR_GZ already exists - will not be overwritten"
   exit 1
fi

# assumptions
COMPOSENAME="docker-compose.yml"
COMPOSE="$IOTSTACK/$COMPOSENAME"
VOLUMES="$IOTSTACK/volumes"
MARIADB_VOLUMES="$VOLUMES/$CONTAINER"
MARIADB_BACKUP="$MARIADB_VOLUMES/db_backup"

# check that container is running
if ! isContainerRunning "$CONTAINER" ; then
   echo "Warning: $CONTAINER not running - backup skipped"
   exit 0
fi

# make sure the database backup directory exists & has correct ownership & mode
[ -d "$MARIADB_BACKUP" ] || sudo mkdir -m 755 -p "$MARIADB_BACKUP"
[ $(stat -c "%U:%G" "$MARIADB_BACKUP") = "$USER:$USER" ] || sudo chown -R $USER:$USER "$MARIADB_BACKUP"
[ $(stat -c "%a" "$MARIADB_BACKUP") = "755" ] || sudo chmod -R 755 "$MARIADB_BACKUP"

# now we can begin
echo "----- Starting $SCRIPT at $(date) -----"

# create the file (sets ownership)
touch "$BACKUP_TAR_GZ"

# the database backup directory needs to be empty
if [ $(ls -1 "$MARIADB_BACKUP" | wc -l) -gt 0 ] ; then
   echo "Erasing $MARIADB_BACKUP"
   sudo rm "$MARIADB_BACKUP"/*
fi


# tell MariaDB to take a backup
echo "Telling $CONTAINER to create a portable backup"
docker exec "$CONTAINER" bash -c "$(preferredCommand mariadb-dump mysqldump) --single-transaction -p\$MYSQL_ROOT_PASSWORD \$MYSQL_DATABASE >/backup/backup.sql"

# perform the backup (relative to ~/IOTstack/volumes/mariadb)
echo "Collecting the backup files into a tar.gz"
sudo tar \
  -czf "$BACKUP_TAR_GZ" \
  -C "$MARIADB_BACKUP" \
  .

# report size of archive
du -h "$BACKUP_TAR_GZ"

echo "----- Finished $SCRIPT at $(date) -----"